# Series 클래스

In [1]:
import pandas as pd

In [4]:
s = pd.Series([1,3,5,7,9]) # 시리즈 객체 생성
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [5]:
print(s.index) # 시리즈의 인덱스를 출력

RangeIndex(start=0, stop=5, step=1)


In [6]:
print(s.values) # 시리즈의 값들을 출력

[1 3 5 7 9]


In [17]:
s = pd.Series([990431, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"]) # 시리즈의 객체의 인덱스 라벨을 지정함
print(s)

서울     990431
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [8]:
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='str')


In [9]:
print(s.values)

[ 990431 3448737 2890451 2466052]


In [16]:
s.name = "인구" # Series 객체 값의 이름
s.index.name = "도시" # 인덱스 라벨의 이름
print(s)

도시
0    Samsung
1      81000
Name: 인구, dtype: object


In [11]:
s.index.name = None
print(s)

서울     990431
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [12]:
print(pd.Series(range(1,5)))

0    1
1    2
2    3
3    4
dtype: int64


In [15]:
s = pd.Series(['Samsung', 81000]) # object 타입으로 생성됨
print(s) 

0    Samsung
1      81000
dtype: object


In [18]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [19]:
data = [1000, 2000, 3000]
s = Series(data)
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [22]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data, index=index) # s = Series(data, index) # s = Series(data=data, index=index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [24]:
s2 = s.reindex(["메로나", "비비빅", "구구콘"])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [26]:
s2 = s2.fillna(0) # NaN을 채우는 함수
print(s2)

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [28]:
price = [42500,42550,41800,42550,42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [29]:
data = {
    "2019-05-31" : 42500, 
    "2019-05-30" : 42550, 
    "2019-05-29" : 41800, 
    "2019-05-28" : 42550, 
    "2019-05-27" : 42650
}
s = Series(data)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [30]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='str')


In [31]:
print(s.index.dtype)

str


In [32]:
print(s.values)

[42500 42550 41800 42550 42650]


In [34]:
s1 = Series([10,20,30])
s2 = Series([10,20,30], index = [1,2,3])

print(s1[0])
print(s2[1])

10
10


In [35]:
s3 = Series([10,20,30], index = ['a', 'b', 'c'])
print(s3['a'])

10


In [37]:
print(s3)

a    10
b    20
c    30
dtype: int64


In [38]:
print(s3.index[0])
print(s3.index[-1])

a
c


In [40]:
s = pd.Series([9904312, 3448737, 2890451, 2466052] , ["서울","부산", "인천", "대구"])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [47]:
print(s[1:3]) # 인덱스 번호 1, 2에 있는 값을 출력함 (3번째는 제외)
print(s["부산":"대구"]) # "부산"에서 "대구"까지 출력함
print(s[1:]) # 1에서 끝까지 출력
print(s[:-1]) # 0부터 -1 전까지 출력

부산    3448737
인천    2890451
dtype: int64
부산    3448737
인천    2890451
대구    2466052
dtype: int64
부산    3448737
인천    2890451
대구    2466052
dtype: int64
서울    9904312
부산    3448737
인천    2890451
dtype: int64


In [48]:
s1 = Series(range(3), ['a','b','c'])
print(s1)

a    0
b    1
c    2
dtype: int64


In [50]:
print(s1.a)
print(s1["a"])

0
0


In [51]:
s = pd.Series([9904312, 3448737, 2890451, 2466052] , ["서울", "부산", "인천", "대구"])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [53]:
print("대구" in s)
print("대전" in s)

True
False


In [54]:
for key, value in s.items():
    print("%s : %d" %(key,value))

서울 : 9904312
부산 : 3448737
인천 : 2890451
대구 : 2466052


In [56]:
# 딕셔너리 원소는 순서를 가지지 않으므로 시리즈의 데이터도 순서를 보장하지 않음, 인덱스라벨을 지정해 순서를 정할 수 있음
s2 = Series({"서울":9631482, "부산":3393191, "인천" : 2632035, "대전" : 1490158}, ["부산", "서울", "인천", "대전"])
print(s2)

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64


In [57]:
from pandas import Series

data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data,index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [62]:
print(s.iloc[0:2]) # iloc 번호로 접근
print(s.loc['메로나':'구구콘']) # loc 키값으로 접근

메로나    1000
구구콘    2000
dtype: int64
메로나    1000
구구콘    2000
dtype: int64


In [64]:
indice = [0, 2]
print(s.iloc[indice])
print(s.iloc[[0,2]])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [66]:
indice = ["메로나", "하겐다즈"]
print(s.loc[indice])
print(s.loc[ ["메로나", "하겐다즈"]])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [67]:
s.loc['메로나'] = 500 # s.iloc[0] = 500. s['메로나'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [68]:
s.loc['비비빅'] = 500 # 없는 키값인 경우 추가
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [74]:
s1 = s.drop('메로나')
print(s1)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [75]:
s = pd.Series([9904312, 3448737, 2890451, 2466052] , ["서울", "부산", "인천", "대구"])
s2 = Series({"서울":9631482, "부산":3393191, "인천" : 2632035, "대전" : 1490158}, ["부산", "서울", "인천", "대전"])
ds = s - s2
print(ds)

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [81]:
print(ds.notnull()) # 값이 null이면 False, 아니면 True
print(ds[ds.notnull()]) # null이 아닌 값만 출력함

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [77]:
s3 = s / 1000000
print(s3)

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64


In [78]:
print(s.values - s2.values)

[ 6511121 -6182745   258416   975894]


In [84]:
rs = (s - s2) / s2 * 100
print(rs)
rs = rs[rs.notnull()]
print(rs)

대구         NaN
대전         NaN
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [85]:
rs["부산"] = 1.63 # 부산 수정
rs["대구"] = 1.41 # 대구는 없으므로 추가됨
print(rs)

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64


In [86]:
del rs["서울"]
print(rs)

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64


In [87]:
from pandas import Series

date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800,42700,42050, 42950,43000], date)
low = Series([42150,42150,41300,42150,42350], date)
print(high)
print('---------------------')
print(low)

6/1    42800
6/2    42700
6/3    42050
6/4    42950
6/5    43000
dtype: int64
---------------------
6/1    42150
6/2    42150
6/3    41300
6/4    42150
6/5    42350
dtype: int64


In [88]:
diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [95]:
print(diff.idxmax(), diff.max())
print(diff.idxmin(), diff.min())

6/4 800
6/2 550


In [96]:
data = {
    "삼성전자" : "전기,전자",
    "LG전자" : "전기,전자",
    "현대차" : "운수장비",
    "NAVER" : "서비스업",
    "카카오" : "서비스업"
}
s = Series(data)
print(s)

삼성전자     전기,전자
LG전자     전기,전자
현대차       운수장비
NAVER     서비스업
카카오       서비스업
dtype: str


In [98]:
print(s.unique()) # 중복 제거
print(s.value_counts()) # 겹치는 값의 갯수를 반환

<StringArray>
['전기,전자', '운수장비', '서비스업']
Length: 3, dtype: str
전기,전자    2
서비스업     2
운수장비     1
Name: count, dtype: int64


In [100]:
import pandas as pd
import numpy as np

s = pd.Series(['선화', '강호', np.nan, '소정', '우영'])
print(s)

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: str


In [106]:
print(s.isnull())
print(s.isna())
print(s[s.notnull()])

0    False
1    False
2     True
3    False
4    False
dtype: bool
0    False
1    False
2     True
3    False
4    False
dtype: bool
0    선화
1    강호
3    소정
4    우영
dtype: str


In [111]:
def remove_comma(x):
    return int(x.replace(",",""))

In [112]:
s = Series(["1,234", "5,678", "9,876"])
result = list(s.map(remove_comma))
print(result)

[1234, 5678, 9876]


In [113]:
from pandas import Series

data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = Series(data,index)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [115]:
cond = s > 42000
print(cond)
print(s[cond]) # print(s[s > 42000]과 같음

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool
2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [116]:
from pandas import Series

data = [3.1, 2.0, 10.1, 5.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data,index)
print(s)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64


In [118]:
# s1 = s.sort_values() # 오름차순 정렬
s1 = s.sort_values(ascending = False) # 내림차순 정렬
print(s1)

000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [121]:
# s2 = s.rank() # 오름차순 기준으로 등수를 나눔
s2 = s.rank(ascending = False) # 내림차순으로 등수를 나눔
print(s2)

000010    3.0
000020    4.0
000030    1.0
000040    2.0
dtype: float64
